version: "3"

services:
  www:
    container_name: shortcut-battle
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: always
    networks:
      - netw
  postgres:
    container_name: postgres-12
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=settings-db
    networks:
      - netw
    tty: true
  pgadmin:
    container_name: pgadmin-4
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    image: dpage/pgadmin4:4.29
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAUL_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - netw

networks:
  netw:
    driver: bridge
